### ISSUE TITLE
[branch: namespace] Exception on /admin/Install.php

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/dotclear#2]
URI:
```php
$_SERVER['REQUEST_URI'] = '/git-dc3/admin/install.php'
```

The `filter_input(INPUT_SERVER, 'REQUEST_URI', FILTER_SANITIZE_FULL_SPECIAL_CHARS)` returns **NULL** and `preg_replace(…)` does not accept NULL for the 3rd argument (line 42).

Env:

MAMP Pro (Apache, PHP 8.1, MySQL 5.7.34) on Mac OS 12, Chrome Canary 99

**Comment by JcDenis** [comment]
Impossible de reproduire, j'ai toujours la bonne url qui ressort :(

**Comment by franck-paul** [comment]
Je vais refaire un test avec tes dernières modifs…

**Comment by franck-paul** [comment]
On peut fermer celui-ci, c'est tout bon \\o/
