### ISSUE TITLE
$blog_id should not be initialized to true, isn't it?

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/dotclear#6]
### Discussed in https://github.com/JcDenis/dotclear/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **franck-paul** June 10, 2022</sup>
https://github.com/JcDenis/dotclear/blob/a20624e94d3106dcdb205c388728d7ff09ea23b4/src/Process/Admin/Handler/BlogPref.php#L35

Proposed:

```
    private $blog_id;
```</div>

**Comment by JcDenis** [comment]
Shoudl be resolved
